//
// Created by rakib on 20/6/2025.
//

#ifndef _DISCRIMINATIVE_DENSE_NEURAL_NETWORK_FRAMEWORK_SINGLE_ATTENTION_HEAD_H
#define _DISCRIMINATIVE_DENSE_NEURAL_NETWORK_FRAMEWORK_SINGLE_ATTENTION_HEAD_H

#endif //_DISCRIMINATIVE_DENSE_NEURAL_NETWORK_FRAMEWORK_SINGLE_ATTENTION_HEAD_H
