//
// Created by rakib on 14/2/2025.
//

#ifndef _DISCRIMINATIVE_DENSE_NEURAL_NETWORK_FRAMEWORK_INITIALIZE_WEIGHTS_H
#define _DISCRIMINATIVE_DENSE_NEURAL_NETWORK_FRAMEWORK_INITIALIZE_WEIGHTS_H

#endif //_DISCRIMINATIVE_DENSE_NEURAL_NETWORK_FRAMEWORK_INITIALIZE_WEIGHTS_H
