//
// Created by rakib on 14/2/2025.
//

#ifndef _DISCRIMINATIVE_DENSE_NEURAL_NETWORK_FRAMEWORK_NEURAL_BLOCKS_H
#define _DISCRIMINATIVE_DENSE_NEURAL_NETWORK_FRAMEWORK_NEURAL_BLOCKS_H

enum class ActivationType {
    RELU,
    SIGMOID,
    TANH,
    LEAKY_RELU,
    SWISH,
    LINEAR,
    NONE
};


#endif //_DISCRIMINATIVE_DENSE_NEURAL_NETWORK_FRAMEWORK_NEURAL_BLOCKS_H
