//
// Created by rakib on 11/2/2025.
//

#ifndef _DISCRIMINATIVE_DENSE_NEURAL_NETWORK_FRAMEWORK_FORWARD_PASS_H
#define _DISCRIMINATIVE_DENSE_NEURAL_NETWORK_FRAMEWORK_FORWARD_PASS_H

#endif //_DISCRIMINATIVE_DENSE_NEURAL_NETWORK_FRAMEWORK_FORWARD_PASS_H
